# Generated by Django 2.0.2 on 2018-02-12 05:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=50)),
                ('alabel', models.CharField(blank=True, max_length=20)),
                ('adate_time', models.DateTimeField(auto_now_add=True)),
                ('acontent', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['-adate_time'],
            },
        ),
    ]
